### ISSUE TITLE
Can't install pytorch3d

### ISSUE THREAD

**Issue by HarrisHongting** [andvg3/LSDM#3]
Hi, I am trying to install pytorch3d on several occasions but without success. I am using Windows platform wsl2 (Linux VM) and have installed cuda11.6 using miniconda. But when I do the step conda install pytorch3d -c pytorch3d, it reminds me of Solving environment: / Segmentation fault. Is there any way to resolve this?

**Comment by andvg3** [comment]
Hi @HarrisHongting ,

Thank you for bringing this important issue to my attention. I have identified that the problem is primarily due to the older version we used during the research, as mentioned in this [link](https://github.com/facebookresearch/pytorch3d/releases/tag/v0.7.3). Could you please try this command for installing older version of Pytorch3D?

`conda install -c pytorch3d -c conda-forge pytorch3d=0.7.3
` 

Looking forward to your response.

Best regards,
An

**Comment by HarrisHongting** [comment]
Hi An,

Thank you for getting back to me. I have successfully installed the old version of pytorch3d. Then, I will try to run this project and find out how it works. Thanks for your help!

Many thanks,
Harris

**Comment by andvg3** [comment]
Great to hear it works. Closed due to issue completed.
